# Generated by Django 2.2.1 on 2019-06-01 14:23
# flake8: noqa

from django.db import migrations, models

from batbox import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=32)),
                ('file', models.FilePathField(match='^[^.].*\\.wav', path=settings.MEDIA_ROOT + 'sessions/', recursive=True)),
                ('processed', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('genus', models.CharField(blank=True, max_length=16)),
                ('species', models.CharField(blank=True, max_length=16)),
                ('recorder_serial', models.CharField(blank=True, max_length=16)),
                ('guano_data', models.TextField(blank=True)),
            ],
        ),
    ]
