# Generated by Django 2.2.2 on 2019-06-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracemap', '0002_audiorecording_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecording',
            name='is_noise',
            field=models.BooleanField(default=False),
        ),
    ]
