# Generated by Django 2.2.2 on 2019-06-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracemap', '0003_audiorecording_is_noise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(blank=True, max_length=32)),
                ('species', models.CharField(blank=True, max_length=32)),
                ('common_name', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
