# Generated by Django 2.2.2 on 2019-06-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracemap', '0004_species'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name': 'Species', 'verbose_name_plural': 'Species'},
        ),
        migrations.AddField(
            model_name='species',
            name='canon_6code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='species',
            name='canon_genus_3code',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
