# Generated by Django 2.2.2 on 2019-06-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracemap', '0005_auto_20190620_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='mdd_id',
            field=models.IntegerField(null=True),
        ),
    ]
