# Generated by Django 2.2.2 on 2019-06-25 18:00

from django.db import migrations, models
from batbox import settings


class Migration(migrations.Migration):
    dependencies = [
        ('tracemap', '0007_auto_20190623_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiorecording',
            old_name='file',
            new_name='audio_file',
        ),
        migrations.AddField(
            model_name='audiorecording',
            name='spectrogram_image_file',
            field=models.FilePathField(
                blank=True,
                match='^[^.].*\\.png',
                null=True,
                path=settings.MEDIA_ROOT + 'processed/spectrograms/',
                recursive=True
            ),
        ),
        migrations.AddField(
            model_name='audiorecording',
            name='subsampled_audio_file',
            field=models.FilePathField(
                blank=True,
                match='^[^.].*\\.wav',
                null=True,
                path=settings.MEDIA_ROOT + 'processed/subsampled/',
                recursive=True
            ),
        ),
    ]
