# Generated by Django 2.2.2 on 2019-06-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracemap', '0008_auto_20190625_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiorecording',
            old_name='recorded_at',
            new_name='recorded_at_utc',
        ),
        migrations.AddField(
            model_name='audiorecording',
            name='recorded_at_iso',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
