dist: xenial
language: python
python:
  - "3.8"
  - "3.9"

install:
  - 'pip install pipenv'
  - 'pipenv install --dev'
  - 'npm install'
  - 'cp batbox/settings.sample.py batbox/settings.py'
# command to run tests
script:
  -  make test