# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.7.3

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - apt-get update && apt-get install -y gnupg apt-transport-https ca-certificates
          - curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
          - echo "deb https://deb.nodesource.com/node_10.x stretch main" | tee /etc/apt/sources.list.d/nodesource.list
          - echo "deb-src https://deb.nodesource.com/node_10.x stretch main" | tee -a /etc/apt/sources.list.d/nodesource.list
          - apt-get update && apt-get install -y unzip nodejs npm
          - pip install pipenv
          - cp batbox/settings.sample.py batbox/settings.py
          - make venv && source venv/bin/activate && make install_dev test
